---
name: image-build
run-name: ${{ github.actor }} is deploying building image 🚀
concurrency: Deployment
on:
  workflow_dispatch
jobs:
  deployment:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v3

      - uses: docker-practice/actions-setup-docker@master
        timeout-minutes: 12

      - name: Install Task
        uses: arduino/setup-task@v1

      - name: build image
        run: |
          docker login -u ${{ secrets.DOCKER_HUB_LOGIN }} -p ${{ secrets.DOCKER_HUB_PASSWORD }}
          task im
